version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5438:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
